import type {Metadata} from "next";
import {Quicksand} from "next/font/google";
import "./globals.css";
import {CardUserImage} from "@/app/components/card-user-image";
import React from "react";
import {AnimatedCursor} from "@/app/components/animated-cursor";
import {Menu} from "@/app/components/menu";


const inter = Quicksand({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
        <body
            className={`${inter.className} bg-background-texture h-screen`}>
        <AnimatedCursor/>

        <div className={"flex h-full justify-center items-center overflow-auto"}>
            <div id="cursor">
                <div id="cursor-outer"></div>
                <div id="cursor-inner"></div>
            </div>
            <div className="container grid mx-auto my-auto md:h-full xl:h-3/4 xl:flex gap-3 ">
                <div className="flex items-center w-full h-full">
                    {/*Menu*/}
                    <Menu/>
                    {/*Card Imagem*/}
                    <CardUserImage/>
                </div>
                <div
                    className={"border bg-gray-900 bg-opacity-90 rounded-3xl border-gray-600 xl:overflow-scroll backdrop-blur-sm  scrollable-container"}>
                    {children}
                </div>
            </div>
        </div>
        </body>
        </html>
    );
}
