import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const itensMenu = [
    {
        id: 1,
        label: 'ABOUT',
        icon: '',
    },
    {
        id: 2,
        label: 'RESUME',
        icon: '',
    },
    {
        id: 3,
        label: 'PROJECTS',
        icon: '',
    },
    {
        id: 4,
        label: 'ARTICLES',
        icon: '',
    },
    {
        id: 5,
        label: 'CONTACT',
        icon: '',
    }
];

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${inter.className} bg-background-texture flex h-screen justify-center items-center`}>
        <div className="container flex mx-auto my-auto h-3/4">
            <div className="container flex h-full items-center w-fit">
                {/*Menu*/}
                <div
                    className={"h-3/4 rounded-full transform skew-y-3 -ml-5 z-40"}>
                    <div
                        className={"w-full p-4 border-2 border-blue-400 h-full rounded-3xl absolute -left-3 top-3 z-0 transform -skew-y-3"}/>
                    <div
                        className={"bg-black border-2 border-gray-600 bg-opacity-60 h-full rounded-full backdrop-blur-md z-0 p-3"}>

                        {
                            itensMenu.map((item) => (
                                <p key={item.id}>
                                    {item.label}
                                </p>
                            ))
                        }
                    </div>
                </div>
                {/*Card Imagem*/}
                <div
                    className={"bg-gradient-to-r from-yellow-400 via-red-500 to-pink-500 h-full w-96 rounded-3xl rotate-y-3d -ml-8"}></div>
            </div>
            <div className={"border-2 bg-gradient-to-tr from-gray-950 via-gray-900 to-gray-700 rounded-3xl border-gray-600 p-3 w-full"}>
                {children}
            </div>
        </div>
        </body>
        </html>
    );
}
