import type {Metadata} from "next";
import {Kdam_Thmor_Pro} from "next/font/google";
import "./globals.css";
import {CardUserImage} from "@/app/components/card-user-image";
import React from "react";
import {AnimatedCursor} from "@/app/components/animated-cursor";
import {Menu} from "@/app/components/menu";


const inter = Kdam_Thmor_Pro({weight: "400", subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
        <body className={`${inter.className} bg-background-texture flex h-screen justify-center items-center`}>
        <AnimatedCursor/>
        <div id="cursor">
            <div id="cursor-outer"></div>
            <div id="cursor-inner"></div>
        </div>
        <div className="container flex mx-auto my-auto h-3/4">
            <div className="container flex h-full items-center w-fit">
                {/*Menu*/}
                <Menu/>
                {/*Card Imagem*/}
                <CardUserImage/>
            </div>
            <div
                className={"border bg-gradient-to-tr from-gray-950 via-gray-900 to-gray-700 rounded-3xl border-gray-600 p-3 w-full"}>
                {children}
            </div>
        </div>
        </body>
        </html>
    );
}
